name: Azure Login with GitHub Action

on:
  workflow_dispatch

permissions:
        contents: read
        id-token: write

jobs:
  Azure_Environment:

    name: "Azure Environemt"
    env:
      AZ_RESOURCE_GROUP: ming-rg-github-action-test
      AKS_NAME: ming-aks-github-action-test

    runs-on: ubuntu-22.04
    environment: development

    steps:
    - name: 'Install Kubectl'
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.30.2' # default is latest stable #azure aks

    - name: 'Az CLI Login with Service Principal'
      #run: |
      #  az login --service-principal -u ${{ secrets.AAD_CLIENT_ID }} -p ${{ secrets.AAD_CLIENT_SECRET }} --tenant ${{ secrets.AAD_TENANT_ID }} 
      #  az account set --subscription ${{ secrets.AAD_SUBSCRIPTION_ID }}
      uses: azure/login@v2
      with:
      #  client-id: ${{ secrets.ADD_CLIENT_ID }}
      #  tenant-id: ${{ secrets.ADD_TENANT_ID }}
      #  subscription-id: ${{ secrets.ADD_SUBSCRIPTION_ID }}
      #
        creds: ${{ secrets.ADD_AZURE_CREDENTIALS }}

    - name: 'Azure CLI script'
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az account show
 

    - name: 'Setup the AKS Environment'
      run: |
        az account set --subscription ${{ secrets.AAD_SUBSCRIPTION_ID }}
        az aks get-credentials --name $AKS_NAME --resource-group $AZ_RESOURCE_GROUP --overwrite-existing

    - name: 'Start the AKS'
      run: |
              #kubectl get node > /dev/null 2&>1; rc=$? || true
              #[ $rc -ne 0 ] && az aks start --name $AKS_NAME --resource-group $AZ_RESOURCE_GROUP || true
        az aks start --name $AKS_NAME --resource-group $AZ_RESOURCE_GROUP 
        kubectl get nodes

    - name: 'Stop the AKS'
      run: |
        az aks stop --name $AKS_NAME --resource-group $AZ_RESOURCE_GROUP
